Core_Seller_Work_Place/CAdmin/Controllers/EInvoiceController.cs
/*
 * 10/1/2014: Create by hientt
 * 20/5/201 update by truongtx on...
 * 26/08/2014 update by quanglt on ...
 * 06/11/2015 update by hientt on ...
 * 28/11/2015 update by duyetnv on ... xóa action sualai
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using EInvoice.Core.IService;
using EInvoice.Core.Domain;
using FX.Core;
using FX.Utils;
using EInvoice.Core;
using FX.Utils.MVCMessage;
using FX.Utils.MvcPaging;
using IdentityManagement.Authorization;
using EInvoice.CAdmin.Models;
using EInvoice.Core.Launching;
using System.Text;
using System.IO;
using EInvoice.CAdmin.IService;
using System.Security.Cryptography.X509Certificates;
using System.Configuration;
using System.Threading;
using System.Web.Caching;
using System.Xml.Linq;
using System.Xml;
using FX.Data;
using IdentityManagement.WebProviders;
using EInvoice.Core.ServiceImp;
using EInvoice.CAdmin.ServiceImp;
using EInvoice.Core.Viewer;

namespace EInvoice.CAdmin.Controllers
{
    class KeyValuesEx
    {
        public string key { set; get; }
        public string value { set; get; }
    }


    [MessagesFilter]
    public class EInvoiceController : ShareController
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(EInvoiceController));

        /// <summary>
        /// Indexes the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="page">The page.</param>
        /// <param name="Pagesize">The pagesize.</param>
        /// <returns></returns>
        /// <Modified>
        /// Author          Dates          Comments
        /// TớiNT          7/10/2018       Create
        /// </Modified>
        [RBACAuthorize(Permissions = "Search_inv")]
        [HttpGet]
        public ActionResult Index(EInvoiceIndexModel model, string resourcecode, int? page, int? Pagesize)
        {
            Log.Info("Start Search Einvoice");
            var pubIn = IoC.Resolve<IPublishInvoiceService>();
            Log.Debug("EInvoiceController Index");
            Company currentCom = ((EInvoiceContext)FXContext.Current).CurrentCompany;

            try
            {
                Log.Info("Index" + currentCom.id + " pattern: " + model.Pattern + " serial: " + model.Serial);

                var membershipCompanyProvider = IoC.Resolve<IRBACMembershipCompanyProvider>();
                var objUser = membershipCompanyProvider.GetUserByNameComid(HttpContext.User.Identity.Name, currentCom.id.ToString(), true);
                if (objUser == null)
                {
                    Messages.AddErrorFlashMessage("User không tồn tại");
                    return RedirectToAction("Index", "Home");
                }

                if (WSHelper.Instance.CheckRoleSerial(currentCom, objUser))
                {
                    model.lstpattern = pubIn.GetLstPatternByUser(currentCom.id, objUser.userid, 1);
                    if (model.lstpattern.Count == 0)
                    {
                        Messages.AddErrorFlashMessage(Resources.Message.MInv_SMesNoRoleSerial);
                        return RedirectToAction("Index", "Home");
                    }
                    model.Pattern = string.IsNullOrEmpty(model.Pattern) ? model.lstpattern[0] : model.Pattern;
                    model.lstserial = pubIn.GetLstSerialByUser(currentCom.id, model.Pattern, 1, objUser.userid);
                }
                else
                {
                    model.lstpattern = pubIn.LstByPattern(currentCom.id, 1);
                    if (model.lstpattern.Count == 0)
                    {
                        Messages.AddErrorFlashMessage(Resources.Message.MInv_SMesNoPubAccess);
                        return RedirectToAction("Index", "Home");
                    }
                    model.Pattern = string.IsNullOrEmpty(model.Pattern) ? model.lstpattern[0] : model.Pattern;
                    model.lstserial = (from p in pubIn.Query where p.Status != 0 && p.RegisterTemplate.InvPattern == model.Pattern && p.RegisterTemplate.ComId == currentCom.id select p.InvSerial).Distinct().ToList();
                }

                int defautPagesize = Pagesize.HasValue ? Convert.ToInt32(Pagesize) : 10;
                int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
                int totalRecords;

                IInvoiceService invSrv = InvServiceFactory.GetService(model.Pattern, currentCom.id);
                IList<IInvoice> lst;
                if (!model.InvNo.HasValue || model.InvNo == null)
                {
                    DateTime? dateFrom = null;
                    DateTime? dateTo = null;
                    if (!string.IsNullOrWhiteSpace(model.FromDate)) dateFrom = DateTime.ParseExact(model.FromDate, "dd/MM/yyyy", null);
                    if (!string.IsNullOrWhiteSpace(model.ToDate)) dateTo = DateTime.ParseExact(model.ToDate, "dd/MM/yyyy", null);
                    if (dateFrom != null && dateTo != null && dateFrom > dateTo)
                    {
                        Messages.AddErrorMessage("Nhập đúng dữ liệu tìm kiếm theo ngày!");
                        dateFrom = dateTo = null;
                    }
                    bool isResourceCode = WSHelper.Instance.CheckResourceCode(currentCom);
                    if (WSHelper.Instance.CheckRoleSerial(currentCom, objUser))
                        lst = invSrv.SearchByCustomer(currentCom.id, model.Pattern, model.Serial, resourcecode, dateFrom, dateTo, (InvoiceStatus)model.Status, model.nameCus, model.code, model.CodeTax, (InvoiceType)model.typeInvoice, currentPageIndex, defautPagesize, out totalRecords, objUser, isResourceCode);
                    else
                        lst = invSrv.SearchByCustomer(currentCom.id, model.Pattern, model.Serial, resourcecode, dateFrom, dateTo, (InvoiceStatus)model.Status, model.nameCus, model.code, model.CodeTax, (InvoiceType)model.typeInvoice, currentPageIndex, defautPagesize, out totalRecords, false, isResourceCode);
                }
                else
                {
                    lst = new List<IInvoice>();
                    IInvoice inv = invSrv.GetByNo(currentCom.id, model.Pattern, model.Serial, model.InvNo.Value);
                    if (inv != null)
                        lst.Add(inv);
                    totalRecords = lst.Count;
                }

                IKeyStoresService keySrv = IoC.Resolve<IKeyStoresService>();
                KeyStores keyStores = keySrv.Query.Where(ks => ks.ComID == currentCom.id).FirstOrDefault();
                string serialCert = "";
                string cert = "";
                decimal typeCert = 0;
                if (keyStores != null)
                {
                    typeCert = keyStores.Type;
                    serialCert = keyStores.SerialCert;
                    ICertificateService iCerSrv = IoC.Resolve<ICertificateService>();
                    Certificate objCeroder = iCerSrv.Query.Where(ce => ce.ComID == currentCom.id && ce.SerialCert.ToUpper().Equals(serialCert)).FirstOrDefault();
                    if (objCeroder != null)
                    {
                        cert = objCeroder.Cert;
                    }
                }
                model.typeCert = typeCert;
                model.serialCert = serialCert;
                model.base64Cert = cert;
                ViewData["resourcecode"] = resourcecode;
                model.PageListINV = new PagedList<IInvoice>(lst, currentPageIndex, defautPagesize, totalRecords);
                AttachmentService _attachmentServiceSrv = IoC.Resolve<AttachmentService>();
                model.PageListAttach = _attachmentServiceSrv.SearhByLstInv(lst);
                Log.Info("End Search Einvoice");
                return View(model);

            }
            catch (UnAuthorizedException e)
            {
                Log.Error("Index -" + e.Message);
                Messages.AddErrorMessage("Có lỗi xảy ra, vui lòng thực hiện lại!");
                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException ex)
            {
                Log.Error("Index -" + ex.Message);
                return Redirect("/Home/PotentiallyError");
            }
            catch (HttpRequestValidationException ex)
            {
                Log.Error("Index -" + ex.Message);
                return RedirectToAction("PotentiallyError", "Home");
            }
        }

        //Tự chọn id của từng hóa đơn để phát hành
        [RBACAuthorize(Permissions = "Release_invInList")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LaunchChoice(string[] cbid, string hdPattern, string Serial)
        {
            Log.Info("LaunchChoice by: " + HttpContext.User.Identity.Name);
            Company currentCom = ((EInvoiceContext)FXContext.Current).CurrentCompany;
            try
            {
                IInvoiceService IInvSrv = InvServiceFactory.GetService(hdPattern, currentCom.id);
                int[] ids = (from s in cbid select Convert.ToInt32(s)).ToArray();
                if (ids.Length < 0)
                {
                    Messages.AddErrorFlashMessage("Bạn chưa chọn hóa đơn.");
                    return RedirectToAction("Index", new { Pattern = hdPattern, Serial = Serial });
                }
                IList<IInvoice> lst = IInvSrv.GetByID(currentCom.id, ids);
                if (lst.Count <= 0)
                {
                    Messages.AddErrorFlashMessage("Bạn chưa chọn hóa đơn.");
                    return RedirectToAction("Index", new { Pattern = hdPattern, Serial = Serial });
                }
                var result = from item in lst
                             from other in lst
                             where item.Pattern != other.Pattern ||
                                   item.Serial != other.Serial
                             select item;

Core_Seller_Work_Place/CAdmin/Views/EInvoice/ACVBANHANGCreate.cshtml
@using EInvoice.Core.Domain
@model EInvoice.Core.Domain.IInvoice
    @{
        ViewBag.Title = "Tạo mới hóa đơn";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                @using (Html.BeginForm("Create", "EInvoice", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    Html.RenderPartial("ACVBANHANGShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-sm-5">
                            </div>
                            <div class="col-sm-4">
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnCreate" />
                                <input type="reset" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnReset" />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack" onclick="document.location = '/EInvoice/Index'" />
                            </div>
                            <div class="col-sm-4">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
            function disableSmt() {
                $('input[type="submit"], input[type="button"], button').disable(true);
            }
</script>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/PESVNCreate.cshtml
@using EInvoice.Core.Domain
@model EInvoice.Core.Domain.IInvoice
    @{
        ViewBag.Title = "Tạo mới hóa đơn";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                @using (Html.BeginForm("Create", "EInvoice", FormMethod.Post))
                {
                Html.RenderPartial("PESVNShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-sm-5">
                            </div>
                            <div class="col-sm-4">
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnCreate" />
                                <input type="reset" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnReset" />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack" onclick="document.location = '/EInvoice/Index'" />
                            </div>
                            <div class="col-sm-4">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
            function disableSmt() {
                $('input[type="submit"], input[type="button"], button').disable(true);
            }
</script>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/PESVNEdit.cshtml
@using EInvoice.Core.Domain
@model  IInvoice
@{
    ViewBag.Title = "INVVATEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/site.css" rel="stylesheet" />
<div class="clear">
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-body">
                @using (Html.BeginForm("Edit", "EInvoice", FormMethod.Post))
                {
                    Html.RenderPartial("PESVNShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <center>
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnSave " />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack " onclick="document.location = '/EInvoice/Index'" />
                            </center>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/SATRAGROUPSELLERCreate.cshtml
@using EInvoice.Core.Domain
@model EInvoice.Core.Domain.IInvoice
    @{
        ViewBag.Title = "Tạo mới hóa đơn";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                @using (Html.BeginForm("Create", "EInvoice", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    Html.RenderPartial("SATRAGROUPSELLERShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-sm-5">
                            </div>
                            <div class="col-sm-4">
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnCreate" />
                                <input type="reset" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnReset" />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack" onclick="document.location = '/EInvoice/Index'" />
                            </div>
                            <div class="col-sm-4">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
            function disableSmt() {
                $('input[type="submit"], input[type="button"], button').disable(true);
            }
</script>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/SATRAGROUPSELLEREdit.cshtml
@using EInvoice.Core.Domain
@model  IInvoice
@{
    ViewBag.Title = "Sửa hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/site.css" rel="stylesheet" />
<div class="clear">
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-body">
                @using (Html.BeginForm("Edit", "EInvoice", FormMethod.Post))
                {
                    Html.RenderPartial("SATRAGROUPSELLERShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <center>
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnSave " />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack " onclick="document.location = '/EInvoice/Index'" />
                            </center>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/SATRAGROUPSELLERMULTIEdit.cshtml
@using EInvoice.Core.Domain
@model  IInvoice
@{
    ViewBag.Title = "Sửa hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/site.css" rel="stylesheet" />
<div class="clear">
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-body">
                @using (Html.BeginForm("Edit", "EInvoice", FormMethod.Post))
                {
                    Html.RenderPartial("SATRAGROUPSELLERMULTIShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <center>
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnSave " />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack " onclick="document.location = '/EInvoice/Index'" />
                            </center>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/SELLERMULTIVATCreate.cshtml
@using EInvoice.Core.Domain
@model  IInvoice
@{
    ViewBag.Title = "Tạo mới hóa đơn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/site.css" rel="stylesheet" />
<div class="clear">
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <div class="box-body">
                @using (Html.BeginForm("Create", "EInvoice", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    Html.RenderPartial("SELLERMULTIVATShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <center>
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnCreate " />
                                <input type="reset" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnReset " />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack " onclick="document.location = '/EInvoice/Index'" />
                            </center>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Core_Seller_Work_Place/CAdmin/Views/EInvoice/SELLERVATCreate.cshtml
@using EInvoice.Core.Domain
@model EInvoice.Core.Domain.IInvoice
    @{
        ViewBag.Title = "Tạo mới hóa đơn";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                @using (Html.BeginForm("Create", "EInvoice", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    Html.RenderPartial("SELLERVATShare", Model);
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-sm-5">
                            </div>
                            <div class="col-sm-4">
                                <input type="submit" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnCreate" />
                                <input type="reset" class="btn btn-primary btn-flat" value="@Resources.Einvoice.BtnReset" />
                                <input type="button" class="btn btn-primary btn-flat btn-cancel" value="@Resources.Einvoice.BtnBack" onclick="document.location = '/EInvoice/Index'" />
                            </div>
                            <div class="col-sm-4">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
            function disableSmt() {
                $('input[type="submit"], input[type="button"], button').disable(true);
            }
</script>